name: first-workflow

on: push

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      -name: setup
       run: make setup

      -name: test
        run: make test
        
      -name: lint 
        run: make lint